from vanilla_ext.advanced import CreateWithInlinesView, UpdateWithInlinesView
from vanilla_ext.formsets import InlineFormSet, GenericInlineFormSet
from vanilla_ext.views import FormSetView, ModelFormSetView, InlineFormSetView, GenericInlineFormSetView
